; MULTIPLICATION
	DATA 	EQU 0X21
	CONT1	EQU	0X22
	CONT2	EQU	0X23
    DE1     EQU 0X24
    DE2     EQU 0X25
    DE3     EQU 0X26
    OP1     EQU 0X27
    OP2     EQU 0X28
    ;UNITS   EQU 0X29
    ;TENS    EQU 0X30

    ;BEGIN
	ORG	0X00
	GOTO	START

;CODE
START
    ;BANK 1
    BSF     STATUS, 5
    BCF     STATUS, 6

	CLRF	TRISB 		; PORT B ALL OUTPUT - LEDS
	CLRF	TRISC		; PORT C ALL OUTPUT - DISPLAY 1
	CLRF	TRISD		; PORT D ALL OUTPUT - DISPLAY 2
	BSF		TRISC, 7	; OPERATION SELECTOR
	BSF		TRISD, 7	; EMITTER RECEIVER SIGNAL DETECTOR

    ;BANK 0
    BCF     STATUS, 5
    BCF     STATUS, 6

	GOTO	MAIN

MAIN
    CALL    MENU
    CALL    DISPRES
	GOTO	MAIN

MENU
	;BTFSC	PORTC, 7
	;CALL	MULT
	;BTFSS	PORTC, 7
	;CALL	DIV
    ;CALL MULT4
    ;RESET OPERANDS
    ;MOVLW   0X00
    ;MOVWF   OP1
    ;MOVWF   OP2
    CALL DIV

    ;RESET OPERANDS
    ;MOVLW   0X00
    ;MOVWF   OP1
    ;MOVWF   OP2
    RETURN

;RES IN OP1
MULT4
    MOVLW   0X05
    MOVWF   OP1
    MOVLW   0X09
    MOVWF   OP2
    MOVLW   0X00

    MOVFW   OP1         ;MOVE OP1 TO W
    ADDWF   OP1, 0X01   ;ADD W TO OP1, STORE IN OP1
    BTFSS   OP2, 0
    MOVLW   0X00
    BTFSC   OP2, 1
    ADDWF   OP1, 0X00   ;ADD W TO OP1, STORE IN W
    RLF     OP1, 0X01   ;ROTATE LEFT OP1, STORE IN OP1
    BTFSC   OP2, 2
    ADDWF   OP1, 0X00   ;ADD W TO OP1, STORE IN W
    RLF     OP1, 0X01   ;ROTATE LEFT OP1, STORE IN OP1
    BTFSC   OP2, 3
    ADDWF   OP1, 0X00   ;ADD W TO OP1, STORE RES IN W
    MOVWF   OP1         ;MOVE RES TO OP1
    RETURN

;RES IN OP1
DIV
    MOVLW   0X0A
    MOVWF   OP2         ;DIVIDEND IN OP2
    MOVLW   0X04        ;DIVISOR IN W

    CLRF    OP1

DIVLOOP
    INCF    OP1, 0X01   ;INC QUOTIENT, STORE IN OP1
    SUBWF   OP2, 0X01   ;SUB DIVIDEND, STORE IN OP2
    BTFSC   STATUS, C   ;CHECK IF SUB WAS NEGATIVE
    GOTO    DIVLOOP
    DECF    OP1, 0X01   ;DEC DIVIDEND, STORE IN OP1
    ADDWF   OP2, 0X01   ;RESTORE NEGATIVE, STORE IN OP2
    RETURN


DISPRES
    MOVLW   0X00
    MOVWF   CONT1       ;TENS
    MOVWF   CONT2       ;UNITS
    MOVLW   0X0A        ;MOVE 10 TO W
    CALL    SUBTENS
    CALL    DISPLAYNUM1
    CALL    DISPLAYNUM2
    RETURN

SUBTENS
    INCF    CONT1, 0X01
    SUBWF   OP1, 0X01
    BTFSC   STATUS, C
    GOTO    SUBTENS
    DECF    CONT1, 0X01
    ADDWF   OP1, 0X01
    RETURN

;DISPLAY 1 == DISPLAY 2
;C0:PIN 15 -- D0:PIN 19 -> DISPLAY 1:E
;C1:PIN 16 -- D1:PIN 20 -> DISPLAY 2:D
;C2:PIN 17 -- D2:PIN 21 -> DISPLAY 4:C
;C3:PIN 18 -- D3:PIN 22 -> DISPLAY 6:B
;C4:PIN 23 -- D4:PIN 27 -> DISPLAY 7:A
;C5:PIN 24 -- D5:PIN 28 -> DISPLAY 9:F
;C6:PIN 25 -- D6:PIN 29 -> DISPLAY 10:G

;DISPLAY NUM ON TENS DISPLAY
DISPLAYNUM1

    MOVFW   CONT1
    MOVWF   DATA
    CALL    GETNUM
    MOVWF   PORTC

    RETURN

;DISPLAY NUM ON UNITS DISPLAY
DISPLAYNUM2

    MOVFW   OP1
    MOVWF   DATA
    CALL    GETNUM
    MOVWF   PORTD

    RETURN

GETNUM

	MOVF	DATA, W
	XORLW	0X00
	BTFSC	STATUS, 2
	GOTO	ZERO

	MOVF	DATA, W
	XORLW	0X01
	BTFSC	STATUS, 2
	GOTO	ONE

	MOVF	DATA, W
	XORLW	0X02
	BTFSC	STATUS, 2
	GOTO	TWO

	MOVF	DATA, W
	XORLW	0X03
	BTFSC	STATUS, 2
	GOTO	THREE

	MOVF	DATA, W
	XORLW	0X04
	BTFSC	STATUS, 2
	GOTO	FOUR

	MOVF	DATA, W
	XORLW	0X05
	BTFSC	STATUS, 2
	GOTO	FIVE

	MOVF	DATA, W
	XORLW	0X06
	BTFSC	STATUS, 2
	GOTO	SIX

	MOVF	DATA, W
	XORLW	0X07
	BTFSC	STATUS, 2
	GOTO	SEVEN

	MOVF	DATA, W
	XORLW	0X08
	BTFSC	STATUS, 2
	GOTO	EIGHT

	MOVF	DATA, W
	XORLW	0X09
	BTFSC	STATUS, 2
	GOTO	NINE

;== DISPLAY PATTERNS ==
ZERO
	MOVLW	B'00111111'
    RETURN
ONE
	MOVLW	B'00001100'
	RETURN

TWO
	MOVLW	B'01011011'
	RETURN

THREE
	MOVLW	B'01011110'
	RETURN

FOUR
	MOVLW	B'01101100'
	RETURN

FIVE
	MOVLW	B'01110110'
	RETURN

SIX
	MOVLW	B'01110111'
	RETURN

SEVEN
	MOVLW	B'00011100'
	RETURN

EIGHT
	MOVLW	B'01111111'
	RETURN

NINE
	MOVLW	B'01111100'
	RETURN

END
