;Set up

;begin program
	ORG	0x00
	GOTO START

;CODE
START
	BSF	STATUS,5	;SET BIT 5(RP0) OF STATUS TO 1, TO MOVE TO BANK 1
	CLRF TRISB		;BITS THAT ARE 0 IN TRISX WIL BE OUTPUT, INPUT IF 1. IN THIS CASE, ALL ARE OUTPUT
	BCF	STATUS, RP0	;SET RP0 TO 0
	BCF	STATUS, 5	;SET BIT 5(RPO) TO 0 AND RETURN TO BANK 0
	MOVLW	0x00	;MOV 0 TO W
	MOVWF	PORTB	;MOV W TO PORTB
	GOTO	INC		;GO TO INC TAG

INC
	ADDLW	0x01	;INC W BY 1
	MOVWF	PORTB	;MOV W TO PORTB
	GOTO	INC		;RETURN TU INC TAG

END